### ISSUE TITLE
VPN not tethering for HTTP Injector (SSH mode)

### ISSUE THREAD

**Issue by frozonecom** [Mygod/VPNHotspot#16] opened 2018-04-26 15:43 UTC
Good day!

I would like to report that I cannot tether my  VPN connection on my Pixel 2 XL to my laptop (win10). I am using HTTP injector for my VPN and when I activate my repeater, when I connect my laptop to the SSID I set up, my computer shows that I have no internet access. Here is the log file. 
[vpnhotspot-8433047002049625497.log](https://github.com/Mygod/VPNHotspot/files/1951922/vpnhotspot-8433047002049625497.log)
[vpnhotspot-4042860800249083886.log](https://github.com/Mygod/VPNHotspot/files/1951923/vpnhotspot-4042860800249083886.log)

**Comment by Mygod** [comment] 2018-04-26 16:37
As far as I can tell, this app is working well on your device, however you also seem to be using some other VPN tethering app that didn't have their rules cleaned up after it is shut down. Can you do a reboot, uninstall/disable those apps and try again?

**Comment by frozonecom** [comment] 2018-04-26 16:56
Hello, I am using PdaNet+ to tether my vpn to my laptop for the meantime. I have uninstalled the app and did a reboot. I tried running your app again and tried connecting my laptop, and still no internet. Here is the log file again. 
It might help to tell you that in my quest to tether vpn connection, I have applied these commands in a terminal emulator with root. Here are the commands I did (though it was only one time and I rebooted after I found out it did not work). I might have created a problem because of it.


Code:
iptables -t filter -F FORWARD
iptables -t nat -F POSTROUTING
iptables -t filter -I FORWARD -j ACCEPT
iptables -t nat -I POSTROUTING -j MASQUERADE
ip rule add from 192.168.43.0/24 lookup 61
ip route add default dev tun0 scope link table 61
ip route add 192.168.43.0/24 dev wlan0 scope link table 61
ip route add broadcast 255.255.255.255 dev wlan0 scope link table 61
[vpnhotspot-5777235737527819074.log](https://github.com/Mygod/VPNHotspot/files/1952185/vpnhotspot-5777235737527819074.log)

Help would be very much appreciated. Thank you!

**Comment by Mygod** [comment] 2018-04-26 19:30
It seems like HTTP Injector (direct SSH mode) seems to be using some very weird DNS mechanisms. Try turning off "DNS Forwarding" in HTTP Injector or switch tunnel type to Shadowsocks instead of SSH (or use other VPN apps) as an workaround for now.

**Comment by darkii321** [comment] 2018-05-31 10:43
ERRO

Folder C:\Users\work\Desktop\VPNHotspot\mobile\build\generated\source\kaptKotlin\debug

Folder C:\Users\work\Desktop\VPNHotspot\mobile\build\generated\source\kaptKotlin\release

3rd-party Gradle plug-ins may be the cause

**Comment by 18774802841** [comment] 2018-06-06 14:18
I am from China to give suggestions to the software. The network name cannot be set up in Chinese.
Unable to establish open wireless networks

**Comment by 18774802841** [comment] 2018-06-06 14:18
I am from China to give suggestions to the software. The network name cannot be set up in Chinese.
Unable to establish open wireless networks

**Comment by 18774802841** [comment] 2018-06-07 02:05
Is it a bit incomprehensible to make it clear? How to build a wireless network without a password

**Comment by Mygod** [comment] 2018-08-26 07:44
I just tested again and it seems like the latest versions are working properly. Closing this.

**Closed by Mygod** 2018-08-26 07:44 UTC
Labels: bug, help wanted
