### ISSUE TITLE
APP闪退/APP Crash

### ISSUE THREAD

**Issue by xiaoweiXX** [Mygod/VPNHotspot#613] opened 2024-09-24 17:02 UTC
我一直使用小米的设备，手机是从小米11 ultra还是小米12S Pro开始，系统是从安卓12还是安卓13开始，我记得从某次安卓大版本更新之后，再打开这个APP就会直接闪退。之后我换了小米14Pro，还有小米平板5Pro和小米平板6Pro，都不能正常打开。我手头还有另一台红米K40（我不清楚这台在全球市场是小米的数字T系列还是POCO子品牌的机型），这台是能够正常使用这个APP的，具体的系统我忘了。
I usually use Xiaomi devices, science Xiaomi 11 ultra or Xiaomi 12S Pro, Android 12 or 13, I remember after I update a Android version, the APP crash every time I open it. I also have Xiaomi 14 Pro, Xiaomi Pad 5 Pro, Xiaomi Pad 6 Pro, all of these devices could not open the APP normally. I also have a Redmi K40 (I forget in global market this devices belong to Xiaomi T series or POCO), this devices can use this APP normally, I forgot the specific system.

**Comment by Mygod** [comment] 2024-09-24 17:30
Logcat please.

**Comment by xiaoweiXX** [comment] 2024-09-25 12:03
> Logcat please.

![Log_2024-9-25_19-59-09.txt](https://github.com/user-attachments/files/17130469/Log_2024-9-25_19-59-09.txt)

我不知道该如何打log，我自己试了一下，不知道效果咋样。
I don't know how to get log, I have a try, don't know if it's right.

**Comment by Mygod** [comment] 2024-09-26 04:37
I am guessing that this is the issue you are facing.

```
Fatal Exception: java.lang.SecurityException
Unknown calling package name 'be.mygod.vpnhotspot'.
android.os.Parcel.createExceptionOrNull (Parcel.java:3057)
android.os.Parcel.createException (Parcel.java:3041)
android.os.Parcel.readException (Parcel.java:3024)
android.os.Parcel.readException (Parcel.java:2966)
com.google.android.gms.common.internal.zzad.getService (com.google.android.gms:play-services-basement@@18.3.0:9)
com.google.android.gms.common.internal.BaseGmsClient.getRemoteService (com.google.android.gms:play-services-basement@@18.3.0:14)
com.google.android.gms.common.internal.BaseGmsClient$LegacyClientCallbackAdapter.onReportServiceBinding (com.google.android.gms:play-services-basement@@18.3.0:2)
com.google.android.gms.common.internal.zzg.zzd (com.google.android.gms:play-services-basement@@18.3.0:1)
com.google.android.gms.common.internal.zza.zza (com.google.android.gms:play-services-basement@@18.3.0:1)
com.google.android.gms.common.internal.zzc.zze (com.google.android.gms:play-services-basement@@18.3.0:3)
com.google.android.gms.common.internal.zzb.handleMessage (com.google.android.gms:play-services-basement@@18.3.0:31)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:224)
android.os.Looper.loop (Looper.java:318)
android.app.ActivityThread.main (ActivityThread.java:8759)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:561)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1013)
```

This probably indicates that you have a broken GMS. Please investigate if this is the case.

**Comment by xiaoweiXX** [comment] 2024-09-26 09:37
> I am guessing that this is the issue you are facing.
> 
> ```
> Fatal Exception: java.lang.SecurityException
> Unknown calling package name 'be.mygod.vpnhotspot'.
> android.os.Parcel.createExceptionOrNull (Parcel.java:3057)
> android.os.Parcel.createException (Parcel.java:3041)
> android.os.Parcel.readException (Parcel.java:3024)
> android.os.Parcel.readException (Parcel.java:2966)
> com.google.android.gms.common.internal.zzad.getService (com.google.android.gms:play-services-basement@@18.3.0:9)
> com.google.android.gms.common.internal.BaseGmsClient.getRemoteService (com.google.android.gms:play-services-basement@@18.3.0:14)
> com.google.android.gms.common.internal.BaseGmsClient$LegacyClientCallbackAdapter.onReportServiceBinding (com.google.android.gms:play-services-basement@@18.3.0:2)
> com.google.android.gms.common.internal.zzg.zzd (com.google.android.gms:play-services-basement@@18.3.0:1)
> com.google.android.gms.common.internal.zza.zza (com.google.android.gms:play-services-basement@@18.3.0:1)
> com.google.android.gms.common.internal.zzc.zze (com.google.android.gms:play-services-basement@@18.3.0:3)
> com.google.android.gms.common.internal.zzb.handleMessage (com.google.android.gms:play-services-basement@@18.3.0:31)
> android.os.Handler.dispatchMessage (Handler.java:106)
> android.os.Looper.loopOnce (Looper.java:224)
> android.os.Looper.loop (Looper.java:318)
> android.app.ActivityThread.main (ActivityThread.java:8759)
> java.lang.reflect.Method.invoke (Method.java)
> com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:561)
> com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1013)
> ```
> 
> This probably indicates that you have a broken GMS. Please investigate if this is the case.
我完全没有头绪，我一直都是正常使用Google Play的，没有遇到过从Google Play上下载的APP会闪退。另外Github的这个版本是否不依赖GMS？我可以用这个版本
I have no idea. I always use Google Play normally, never seen APP crash which is download on Google Play. Besides, isn't the Github version depends on Google Play? I can use this version.

**Comment by xiaoweiXX** [comment] 2024-09-26 09:44
> I am guessing that this is the issue you are facing.
> 
> ```
> Fatal Exception: java.lang.SecurityException
> Unknown calling package name 'be.mygod.vpnhotspot'.
> android.os.Parcel.createExceptionOrNull (Parcel.java:3057)
> android.os.Parcel.createException (Parcel.java:3041)
> android.os.Parcel.readException (Parcel.java:3024)
> android.os.Parcel.readException (Parcel.java:2966)
> com.google.android.gms.common.internal.zzad.getService (com.google.android.gms:play-services-basement@@18.3.0:9)
> com.google.android.gms.common.internal.BaseGmsClient.getRemoteService (com.google.android.gms:play-services-basement@@18.3.0:14)
> com.google.android.gms.common.internal.BaseGmsClient$LegacyClientCallbackAdapter.onReportServiceBinding (com.google.android.gms:play-services-basement@@18.3.0:2)
> com.google.android.gms.common.internal.zzg.zzd (com.google.android.gms:play-services-basement@@18.3.0:1)
> com.google.android.gms.common.internal.zza.zza (com.google.android.gms:play-services-basement@@18.3.0:1)
> com.google.android.gms.common.internal.zzc.zze (com.google.android.gms:play-services-basement@@18.3.0:3)
> com.google.android.gms.common.internal.zzb.handleMessage (com.google.android.gms:play-services-basement@@18.3.0:31)
> android.os.Handler.dispatchMessage (Handler.java:106)
> android.os.Looper.loopOnce (Looper.java:224)
> android.os.Looper.loop (Looper.java:318)
> android.app.ActivityThread.main (ActivityThread.java:8759)
> java.lang.reflect.Method.invoke (Method.java)
> com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:561)
> com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1013)
> ```
> 
> This probably indicates that you have a broken GMS. Please investigate if this is the case.

我感觉和GMS没关系，小米的旗舰设备一直都搭载GMS。并且我第一次遇到APP闪退是安卓大版本更新之后，我一直以为闪退的问题是和安卓版本的适配有关。
I think that there's no relationship with GMS,  Xiaomi's flagship devices always have GMS. And the first time I seen APP crash is after Android version update, I always thought that the crash problem was related to the adaptation of the Android version.

**Comment by xiaoweiXX** [comment] 2024-09-28 12:21
> I am guessing that this is the issue you are facing.
> 
> ```
> Fatal Exception: java.lang.SecurityException
> Unknown calling package name 'be.mygod.vpnhotspot'.
> android.os.Parcel.createExceptionOrNull (Parcel.java:3057)
> android.os.Parcel.createException (Parcel.java:3041)
> android.os.Parcel.readException (Parcel.java:3024)
> android.os.Parcel.readException (Parcel.java:2966)
> com.google.android.gms.common.internal.zzad.getService (com.google.android.gms:play-services-basement@@18.3.0:9)
> com.google.android.gms.common.internal.BaseGmsClient.getRemoteService (com.google.android.gms:play-services-basement@@18.3.0:14)
> com.google.android.gms.common.internal.BaseGmsClient$LegacyClientCallbackAdapter.onReportServiceBinding (com.google.android.gms:play-services-basement@@18.3.0:2)
> com.google.android.gms.common.internal.zzg.zzd (com.google.android.gms:play-services-basement@@18.3.0:1)
> com.google.android.gms.common.internal.zza.zza (com.google.android.gms:play-services-basement@@18.3.0:1)
> com.google.android.gms.common.internal.zzc.zze (com.google.android.gms:play-services-basement@@18.3.0:3)
> com.google.android.gms.common.internal.zzb.handleMessage (com.google.android.gms:play-services-basement@@18.3.0:31)
> android.os.Handler.dispatchMessage (Handler.java:106)
> android.os.Looper.loopOnce (Looper.java:224)
> android.os.Looper.loop (Looper.java:318)
> android.app.ActivityThread.main (ActivityThread.java:8759)
> java.lang.reflect.Method.invoke (Method.java)
> com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:561)
> com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1013)
> ```
> 
> This probably indicates that you have a broken GMS. Please investigate if this is the case.

Do I need to pass safety net check? After I unlock the bootloader, I can't pass safety net check, and I don't want to use module to pass the check.

**Comment by Mygod** [comment] 2024-09-28 19:29
No.

**Comment by Mygod** [comment] 2024-10-21 06:36
Since I can see that multiple Xiaomi devices having this issue, please report this to Xiaomi and see if they can fix it.

**Comment by Mygod** [comment] 2024-10-22 00:30
Never mind I found a fix.

**Comment by Mygod** [comment] 2024-10-22 00:33
Fixed via https://github.com/Mygod/VPNHotspot/commit/a33e3398cb848b9b286b773f11115ad745870f3c.

**Comment by Mygod** [comment] 2024-10-22 20:25
Please check and see if [v2.18.1](https://github.com/Mygod/VPNHotspot/releases/tag/v2.18.1) fixes this issue.

**Comment by xiaoweiXX** [comment] 2024-10-23 04:08
> Please check and see if [v2.18.1](https://github.com/Mygod/VPNHotspot/releases/tag/v2.18.1) fixes this issue.

NO, it still crash.

**Comment by xiaoweiXX** [comment] 2024-10-23 04:13
> Please check and see if [v2.18.1](https://github.com/Mygod/VPNHotspot/releases/tag/v2.18.1) fixes this issue.

It's very strange, every time I open it, I can use it normally for about 1 or 2 seconds, then it crash.

**Comment by Mygod** [comment] 2024-10-23 05:10
Yes indeed. This issue was not fixed. A proper fix would need to come from either Google or Xiaomi.

**Closed** 2024-10-23 22:59 UTC
Labels: wontfix, vendor-specific

**Comment by itsHenry35** [comment] 2024-12-21 14:10
Are you using hidemyapplist? Recently I came across the same problem, however, everything worked again when I removed hidemyapplist

**Comment by xiaoweiXX** [comment] 2024-12-30 10:46
> Are you using hidemyapplist? Recently I came across the same problem, however, everything worked again when I removed hidemyapplist

Yes. How could HMA affect VPNHotspot?🤔

**Comment by itsHenry35** [comment] 2024-12-30 11:00
> > Are you using hidemyapplist? Recently I came across the same problem, however, everything worked again when I removed hidemyapplist
> 
> Yes. How could HMA affect VPNHotspot?🤔

No idea~ Probably further inverstigation into HMA's source code is required by somone professional. 🥱

**Comment by Mygod** [comment] 2024-12-30 19:27
This is caused by a remote exception probably originating from gms. You should not apply HMA to gms.

**Comment by xiaoweiXX** [comment] 2024-12-30 21:20
> This is caused by a remote exception probably originating from gms. You should not apply HMA to gms.

OK, I'll have a try. I just don't want GMS detect my root APPs to pass the SafetyNet. (Even I failed, I didn't pass the SafetyNet test. I need a magisk module to pass, which I don't want to use.)

**Comment by xiaoweiXX** [comment] 2024-12-30 21:26
> This is caused by a remote exception probably originating from gms. You should not apply HMA to gms.

Yes, after stop apply GMS, it works normally. But I still feel strange, I didn't meet any similar saturation before. Every APP works normally expect VNPHotspot.
