### ISSUE TITLE
Bug : Pixel 5 Android 11

### ISSUE THREAD

**Issue by knuxyl** [Mygod/VPNHotspot#192] opened 2020-11-08 18:44 UTC
You can turn on WiFi hotspot with app but you cannot turn it off on Android 11 on the Pixel 5. No pixel 5 software updates have changed this. There is no error, it just doesn't do anything. You can turn if off through settings or tile. Other than the usual tethering hardware acceleration not working, everything is working great. Thanks![vpn logs](https://drive.google.com/file/d/14OUksbCJUBQ8thhi3DGK2RIcee3oGLRI/view?usp=drivesdk) 
If link doesnt work, here is direct
https://drive.google.com/file/d/14OUksbCJUBQ8thhi3DGK2RIcee3oGLRI/view?usp=drivesdk

**Comment by Mygod** [comment] 2020-11-08 20:59
Try a reboot? Was the app working before?

**Comment by knuxyl** [comment] 2020-11-08 21:35
Reboot does not fix it and it has never. Also, app systemizer doesnt work for android 11 so i am unable to test if making it a system app would make a difference

**Comment by Mygod** [comment] 2020-11-09 00:21
On Android 11, there is no need to install it as system app.

**Comment by Mygod** [comment] 2020-11-17 18:18
Closing this as I cannot reproduce.

**Closed by Mygod** 2020-11-17 18:18 UTC
