### ISSUE TITLE
HTC 10: Cannot change Repeater network name

### ISSUE THREAD

**Issue by daohoangson** [Mygod/VPNHotspot#81] opened 2019-03-05 08:15 UTC
After entering new name and click Save, the snack bar only shows "null". I have check the log and found this:

```
03-05 14:28:01.617 18453 18453 W RepeaterManager: kotlin.KotlinNullPointerException
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at be.mygod.vpnhotspot.net.wifi.P2pSupplicantConfiguration$content$2$1.invoke(P2pSupplicantConfiguration.kt:107)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at be.mygod.vpnhotspot.net.wifi.P2pSupplicantConfiguration$content$2$1.invoke(P2pSupplicantConfiguration.kt:17)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at be.mygod.vpnhotspot.util.RootSession$Companion.use(RootSession.kt:38)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at be.mygod.vpnhotspot.net.wifi.P2pSupplicantConfiguration$content$2.invoke(P2pSupplicantConfiguration.kt:48)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at be.mygod.vpnhotspot.net.wifi.P2pSupplicantConfiguration$content$2.invoke(P2pSupplicantConfiguration.kt:17)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at be.mygod.vpnhotspot.net.wifi.P2pSupplicantConfiguration.getContent(Unknown Source:7)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at be.mygod.vpnhotspot.net.wifi.P2pSupplicantConfiguration.update(P2pSupplicantConfiguration.kt:119)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at be.mygod.vpnhotspot.manage.RepeaterManager.onEditResult(RepeaterManager.kt:176)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at be.mygod.vpnhotspot.manage.TetheringFragment.onActivityResult(TetheringFragment.kt:136)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at be.mygod.vpnhotspot.AlertDialogFragment.onClick(AlertDialogFragment.kt:33)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at android.os.Handler.dispatchMessage(Handler.java:105)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at android.os.Looper.loop(Looper.java:180)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at java.lang.reflect.Method.invoke(Native Method)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
03-05 14:28:01.617 18453 18453 W RepeaterManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
```

I have cloned the repo and debug in Android Studio, looks like `target` is null but `RepeaterService.persistentSupported` is true so the `if (target == null && !RepeaterService.persistentSupported)` code block doesn't run. 

Every time I turn on the Repeater, a new network name is generated. The `/data/misc/wifi/p2p_supplicant.conf` file looks something like this (a new block is generated each time):

```
ctrl_interface=/data/misc/wifi/sockets
driver_param=use_p2p_group_interface=1p2p_device=1
update_config=1
device_name=Android_32eb
device_type=10-0050F204-5
config_methods=display push_button keypad virtual_push_button physical_display 
p2p_add_cli_chan=1
hs20=1
interworking=1
pmf=1
sched_scan_interval=75

network={
	ssid="DIRECT-eu-Android_32eb"
	bssid=82:7a:bf:3d:c3:a4
	psk="Z05Xp2z4"
	proto=RSN
	key_mgmt=WPA-PSK
	pairwise=CCMP
	auth_alg=OPEN
	mode=3
	disabled=2
}

network={
	ssid="DIRECT-Kn-Android_32eb"
	bssid=82:7a:bf:3d:c3:a4
	psk="AEmVmoQF"
	proto=RSN
	key_mgmt=WPA-PSK
	pairwise=CCMP
	auth_alg=OPEN
	mode=3
	disabled=2
}
```

I'm not sure whether this is related to #31. Is it a vendor issue? Let me know if I can help to resolve this.

**Comment by Mygod** [comment] 2019-03-09 13:26
Try v2.3.1.

**Comment by daohoangson** [comment] 2019-03-10 02:44
I don't think the fix works. My steps:

- Join beta program, update to 2.3.1
- Turn on Repeater
- Tap Network Name
- Enter "xxx" as the name
- Save

Expect: network name is changed. Actual: App crashes.

Tried again (same steps as above). Actual: Repeater turns itself off (no crash).

**Comment by Mygod** [comment] 2019-03-10 04:13
Second time sounds like expected behavior.

**Comment by daohoangson** [comment] 2019-03-10 08:47
Oh, that was expected? I did try turning on Repeater after the second attempt and the network name was not the one I entered earlier ("xxx").

**Comment by Mygod** [comment] 2019-03-12 06:04
It seems like HTC 10 now [uses a different format](https://github.com/evait-security/android-wifi-key-view/blob/ae1fabd89bee1ce409322e7dba2fbeec9f357433/app/src/main/java/wkv/android/evait/com/wifikeyview/MainActivity.java#L249-L252) for Wi-Fi. Sorry nothing I can do for now.

**Comment by daohoangson** [comment] 2019-03-12 07:29
Oh, interesting. Do you have further document (other than the link above) for me to dig into? I will try to debug it on my device if possible.

It's worth noting that the Repeater still works. My laptop connected to the network and traffic is routed through the VPN correctly. There are only issue with the network name: it changed semi randomly each time, making it hard to configure my Chromecast 😆

**Comment by Mygod** [comment] 2019-03-12 07:40
If it changes every time (say after each reboot of your device), I'd say it would also be a duplicate of #31. I'll close this for now. You can read #31 for some of my failed attempts at fixing this. This is really only occurring on some of the devices. Unfortunately, I don't have a lot of time figuring out the intricacies of AOSP but feel free to dig deeper.

**Closed by Mygod** 2019-03-12 07:40 UTC
Labels: vendor-specific

**Comment by daohoangson** [comment] 2019-03-12 08:24
It changes every time I turn on the Repeater actually. Thank you for the pointer, I will look into the other issue and try debugging on my device.

**Comment by denizaydemir** [comment] 2020-03-14 22:22
@daohoangson Hi, anything new came up?

**Comment by daohoangson** [comment] 2020-03-15 08:31
@denizaydemir nope, I have switched device and no longer use this app. Sorry.
