### ISSUE TITLE
Set a fixed login/password combination on the "temporary" hotspot

### ISSUE THREAD

**Issue by neocult-de** [Mygod/VPNHotspot#20] opened 2018-05-13 10:11 UTC
Additionally to the Repeater-function that helps to provide VPN through another Wifi, the Tethering dialogue in VPN Hotspot allows to provide VPN through Mobile connection to toher devices. But why is there no corresponding option to set login/password on the "Temporary Wi-Fi hotspot"? That would be a great deal to repeatedly share the mobile connection to other devices with the proper VPN connection in place.

There might be a specific reason why that is or I might have overlooked how to do that in the UI, but if that would be possible to integrate, it would make another great feature. Especially in "regulated" countries e.g. China, to help out others connecting to the world.

**Comment by Mygod** [comment] 2018-05-13 15:28
Use system tethering instead. And yes I'm not sure how to specify credentials for temporary hotspot for now but I'd suggest if that's what you want, you might want to use system Wi-Fi hotspot instead.

**Comment by neocult-de** [comment] 2018-05-13 20:49
I guess the wlan0 interface, activatable after initiating the system Wi-Fi hotspot should do the trick. Doesn´t work for me though, unbearable amout of constant connection interruptions and half of the internet is not usable (DNS requests and certain cdns like YouTube work though), while the option Temporary Hotspot works always and continously like a charm. Will give it a bit more testing. Thank you very much for the quick reply!

**Comment by Mygod** [comment] 2018-05-14 08:31
Oh do you have IPv6 connectivity on your mobile data? If so, it could be the cause of interruptions for wlan0. I will try to write a fix sometime.

Yeah temporary hotspot is meant to be temporary and SSID and passwords are generated by Android (it's an Oreo feature). I'm not sure if there's some way to change it but I haven't looked into it either since I originally added this feature just for fun. :P

**Comment by neocult-de** [comment] 2018-05-14 09:55
Yeah, indeed. Mobile connections here, mine included, all actually have IPv6 connectivity. A fix would be amazing. Good luck on that. If you need any data provided, let me know.

**Comment by Mygod** [comment] 2018-06-03 01:39
Please give [1.3.1-alpha](https://github.com/Mygod/VPNHotspot/releases/tag/1.3.1) a go and see how that goes. Make sure to enable the "disable IPv6 tethering" option.

**Comment by Mygod** [comment] 2018-06-04 08:31
It's not possible to change temporary hotspot SSID/password without using Xposed. Closing this for now.

**Closed by Mygod** 2018-06-04 08:31 UTC
Labels: enhancement

**Comment by Mygod** [comment] 2018-06-16 00:32
Hi again, [1.3.4](https://github.com/Mygod/VPNHotspot/releases/1.3.4) introduced a masquerade option that might help with your connection issues. Give it a try.

**Comment by moralrebuild** [comment] 2018-07-05 17:09
@Mygod  Having a fixed credential for wifi Repeater mode is very convenient when carrying chromecast around. Could you please elaborate how to achieve it by using Xposed? Thanks for your great open source work!

**Comment by Mygod** [comment] 2018-07-06 02:03
You can change credentials for Repeater mode without Xposed. If you're talking about temporary hotspot, you need to change the method mentioned at https://github.com/Mygod/VPNHotspot/issues/20#issuecomment-394275751.

I recommend to use system hotspot + tethering VPN instead of trying to make temporary hotspot work with custom credentials.

**Comment by moralrebuild** [comment] 2018-07-06 03:13
@Mygod Repeater should be more friendly choice for mobile bill when free wifi hotspot is available. But both of my android 8.1.0 devices (nexus 6P w/ google stock firmware and nexus 6 w/ Lineage 15.1) failed to keep the customized SSID/password in this mode, instead one-time credential is always generated.

**Comment by Mygod** [comment] 2018-07-06 08:31
However it's working fine on both my 8.1 devices. Do you have Xposed etc?

**Comment by moralrebuild** [comment] 2018-07-07 11:10
I just installed Xposed but still no joy. Does it need some additional modules?
