### ISSUE TITLE
WiFi hotspost toggle not synced

### ISSUE THREAD

**Issue by FrancYescO** [Mygod/VPNHotspot#164] opened 2020-06-15 12:22 UTC
To get it working i have to tap on the WiFi Hotspot toggle that will turn on system hotspot, than on the "wlan1" toggle, if this toggle is not on the traffic goes through normal 4G connection

The only way to turn off hostspot is via the system toggle

Video: 
![videoplayback](https://user-images.githubusercontent.com/4574593/84656854-a377d380-af13-11ea-95cd-ff1c298ab6a7.gif)

Log: https://ctrlv.it/txt/233399/4205981673

Plus:
- it's not clear where to find the "temporary hotspot" password
- there are no check for no root permissions

**Comment by Mygod** [comment] 2020-06-15 17:28
Thanks for reporting! The toggle is definitely supposed to be toggled. Please try [this apk](https://mygod.be/resources/userscloud/uzjpoh19trk1) and export debug information again.

For your questions:

* Please find passwords in the top right once you have enabled temporary hotspot.
* It looks like the app already has root so that seems fine to me.

**Comment by FrancYescO** [comment] 2020-06-15 17:42
Tested, nothing changes.
https://ctrlv.it/txt/233413/773962352

Yep actually have the root permissions but initially i haven't give the permissions for SU (idk why the poupup wasn't shown), so the app was trying to issue the commands in background obviously getting permission denied, is just something to take care and show a warning about somehow.

**Comment by Mygod** [comment] 2020-06-15 17:46
```
tetherableWifiRegexs: [softap0, wlan0, wigig0]
```

It seems like the issue is that the system is not configured to recognize `wlan1` as a Wi-Fi hotspot candidate. Does system setting work fine?

**Comment by FrancYescO** [comment] 2020-06-15 17:48
sure, actually i'm just using 5GHz for wifi hotspot, i've also tried to set it to 2.4 but the app behaviour is the same

**Comment by Mygod** [comment] 2020-06-15 19:03
Closing this as third-party bug.

**Closed by Mygod** 2020-06-15 19:03 UTC
Labels: question, vendor-specific

**Comment by FrancYescO** [comment] 2020-06-15 20:44
not possible to just use the miui setting property (idk how to find it) if present?

**Comment by Mygod** [comment] 2020-06-15 20:46
Yes but I do not wish to hardcode wlan1 on there. After all that switch is just a system shortcut.
